### ISSUE TITLE
\documentclass[ms]{osudissert96} does not produce intended result

### ISSUE THREAD

**Issue by garrettdowd** [swarnendubiswas/ohio-state-coe-dissertation-template#1]
Formatting for Master's Thesis in `dissertation.tex` using `\documentclass[ms]{osudissert96}` does not produce correct format. [ma] and [masters] also incorrect.

Actual result
```
Ohio State College of Engineering MS/PhD DissertationTemplate
Candidacy proposal
By
Swarnendu Biswas, XX, YY
Graduate Program in Computer Science and Engineering
The Ohio State University
2019
Candidacy Proposal Committee:
WW, Advisor
```

Compiled using Overleaf

**Comment by swarnendubiswas** [comment]
I am unable to reproduce it. It works for me with `[phd]`, `[ms]`, `[ma]`, and `[masters]`. I tried with both TeX Live 2019 and Overleaf.

**Comment by garrettdowd** [comment]
Thanks for looking into it.
Hmm. That is weird. I downloaded the repository as a zip file and directly uploaded it to Overleaf. The only modification I made is the one specified in the original issue `\documentclass[ms]`

It should include this line (among other differences)
```
Presented in Partial Fulfillment of the Requirements for the Degree
Master of Science in the Graduate School of The Ohio State
University
```
but it does not.

**Comment by swarnendubiswas** [comment]
Hmm you are right, this is an issue with the `ms` option. I will look into it, pull requests are definitely welcome.

**Comment by swarnendubiswas** [comment]
@garrettdowd I think I have fixed the issue, could  you please check and confirm? I had never tried the `ms` or `masters` control path.

**Comment by swarnendubiswas** [comment]
Closing this since I think this has been fixed, and there was no response back from the OP.
